### ISSUE TITLE
Mark Messages read in Folder and the subfolders recursively not displayed as expected

### ISSUE THREAD

**Issue by hsvia** [RealRaven2000/QuickFolders#109]
Hi, 
I know that there is a closed feature request and an implementation  but:
The command "mark folder read" currently does not affect the full sub-tree,
even in case the option "Mark Folder Read (recursive)" is active.
It works in the 1st level only.
**I use a very deep nested folder structure.**
Though it is very boring to click every subfolder individually....

**Comment by RealRaven2000** [comment]
So this was apparently issue #3 (a very early issue after changing the bug database from mozdev.org) - which is supposed to an extra command in the context menu. I think this supposed to bubble above the separate "Mail Commands" menu and show on top. Apparently this only shows up if there are no unread mails in the folder itself:

Thunderbird 68:
![image](https://user-images.githubusercontent.com/6314674/107773347-6af3f800-6d35-11eb-9389-9b5ba392c838.png)

Thunderbird 78:
![image](https://user-images.githubusercontent.com/6314674/107773387-7f37f500-6d35-11eb-9952-8c009d616b55.png)

as workaround you can first click the "ordinary" item "_Mark Folders as read_", then right-click again, and select "_mark folder + subfolders read_". I think it might be correct if both items were shown in case there are unread items in any subfolders.

**Comment by RealRaven2000** [comment]
Fixed in 5.3 / 4.20 - released 22/02/2021

**Comment by boardtc** [comment]
> So this was apparently issue #3 (a very early issue after changing the bug database from mozdev.org) - which is supposed to an extra command in the context menu. I think this supposed to bubble above the separate "Mail Commands" menu and show on top. Apparently this only shows up if there are no unread mails in the folder itself:
> 
> Thunderbird 68: ![image](https://user-images.githubusercontent.com/6314674/107773347-6af3f800-6d35-11eb-9389-9b5ba392c838.png)
> 
> Thunderbird 78: ![image](https://user-images.githubusercontent.com/6314674/107773679-e8b80380-6d35-11eb-8678-810af335792a.png)
> 
> as workaround you can first click the "ordinary" item "_Mark Folders as read_", then right-click again, and select "_mark folder + subfolders read_". I think it might be correct if both items were shown in case there are unread items in any subfolders.

How do I see this menu item, my right click does not show the top item added by QuickFolders. I am running TB 91.7.

**Comment by RealRaven2000** [comment]
> > as workaround you can first click the "ordinary" item "_Mark Folders as read_", then right-click again, and select "_mark folder + subfolders read_". I think it might be correct if both items were shown in case there are unread items in any subfolders.
> 
> How do I see this menu item, my right click does not show the top item added by QuickFolders. I am running TB 91.7.

QuickFolders Settings / Advanced / Menu Configuration:

![image](https://user-images.githubusercontent.com/6314674/182250146-64b97b2d-ef84-4ee2-bec6-79c14b5692e2.png)

**Comment by boardtc** [comment]
Sorry for the late reply, but I still have this issue. I have had the selected option checked but my problem is I do not see the mark folders + subfolders Read menu option.
Maybe it's a paid-only option?
![menu](https://github.com/RealRaven2000/QuickFolders/assets/214808/4ccb7c67-db7a-442e-bd6e-24113777cc25)

**Comment by RealRaven2000** [comment]
> Sorry for the late reply, but I still have this issue. I have had the selected option checked but my problem is I do not see the mark folders + subfolders Read menu option. Maybe it's a paid-only option? 

you have to look in the right-cli k menu on the QuickFolders tabs (which represent specific folders) :

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/ff721d79-c7c6-4489-8e40-18dc54b0d355)

- You will only see the command if QuickFolders detects unread messages
- You can enable / disable the commands in `QF Settings » Advanced » Menu configuration » Mail Commands`

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/75edae1b-f0ec-4ca2-8a38-0834ff0eccfc)

**Comment by boardtc** [comment]
I have only used TB tabs. After playing with it for 5 minutes I have not figured out how to open a QuickFolder tab, how do I do it?

**Comment by RealRaven2000** [comment]
I hope I am understanding your question right - first of all - if you haven't created any QuickFolders tabs yet you should see a label like this:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/6a1f9bfc-1313-409d-9a66-27369e30dd26)

"Drag folders here to create a tab"

so this should entice a new user to drag any folder up to the toolbar area:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/6961b428-81ea-41cb-8352-9f183729dd0f)

this generats a tab which acts as a shortcut to the folder:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/5a1b57ca-a762-4645-8c40-b6f2e7198b74)

you then have the commands on the right-click menu of any of the QuickFolders Tab:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/ed85d0de-0b9d-4949-81f9-b8c489fa082e)

it also gives you the list of subfolders. The QF tabs also act as drop targets for emails so you can easily move files to your favorite locations.

**Comment by RealRaven2000** [comment]
sorry - posted the wrong screenshot - see the next comment

**Comment by RealRaven2000** [comment]
My previous comment had the wrong screenshot - so here goes again:

PS: if you want to use the command on _any_ folder (even the ones that are not displayed as QF tabs) you can use the Current Folder Bar in the center of the screen:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/6bd37377-d208-4740-ab82-2660e5cf0293)


it represents the folder you are currently looking at.

**Comment by boardtc** [comment]
@RealRaven2000 Fantastic education, many thanks. I had inbox tab there that I did not realise, when removed I got the message and started learning from your posts. I got it all now, brilliant, thanks for taking the time./

Up to now I have only really used it for being able to find folders easily. (Or is that Quick filters, sorry)

>>The QF tabs also act as drop targets for emails so you can easily move files to your favorite locations.

Interesting idea, they become shortcuts. I normally use the context menu, Move to -> Recent -> folder.  I also just noticed the Quick Move option on the toolbar, never noticed it before.

I definitely will use the QF tabs now as my TB creaks moving between tabs on the main tree.

Incidentally, this may be a known bug related to dark theme, but my inbox tab is not very readable unless active when the text turns white. That said the screenshot below is more readable than on my monitor, perhaps due to glare then...
![image](https://github.com/RealRaven2000/QuickFolders/assets/214808/6266c3e9-86b1-4f0a-9ab4-94bb2e6f32a2)

**Comment by RealRaven2000** [comment]
> Up to now I have only really used it for being able to find folders easily. (Or is that Quick filters, sorry)

I guess that's the quickMove / quickJump field you are referring to - and yes that's a QuickFolders feature. quickFilters is for creating new filters easily.

> 
> > > The QF tabs also act as drop targets for emails so you can easily move files to your favorite locations.
> 
> Interesting idea, they become shortcuts. I normally use the context menu, Move to -> Recent -> folder. I also just noticed the Quick Move option on the toolbar, never noticed it before.

this is kind of funny - the shortcuts and the quickMove are the main features of QuickFolders. I am wondering what you have used it for? You can also configure a recent folders tab in QF general settings:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/27fe4efd-ed1d-4d46-af9d-c6646fd7b932)

it will be added as first thing:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/ebd17d0c-986f-4699-861e-bc94eb3f915f)

**Comment by RealRaven2000** [comment]
> Incidentally, this may be a known bug related to dark theme, but my inbox tab is not very readable unless active when the text turns white. That said the screenshot below is more readable than on my monitor, perhaps due to glare then...

You can set the colors (depending on varying state) in QuickFolders settings on the Page "Bling my Tabs":

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/ff430f46-e99c-435d-a9ba-3bae6214d686)

click the preview tabs to select a preset.

**Comment by skleiber** [comment]
In MacOS 14.6.1 with Thunderbird 115.14.0 (and ThB 128.1.0) and QuickFolders v6.6.1 there is no "Mark Folder as Read" or "Mark folder + subfolders Read" in the context menu ... neither in the context menu of the tabs, nor in the current folder bar.

Additional info:
- Pro license of QuickFolders
- no other addons active
- no userChrome.css / userContent.css

<img width="635" alt="MacOS-14 6-ThB-115 14 0-QuickFolders-6 6 1-Options-General" src="https://github.com/user-attachments/assets/8c22c7f7-934e-41c3-b22d-4e905be97ce7">

<img width="632" alt="MacOS-14 6-ThB-115 14 0-QuickFolders-6 6 1-Options-Advanced" src="https://github.com/user-attachments/assets/184e9852-a129-4a07-b327-9c0493d84172">

<img width="786" alt="MacOS-14 6-ThB-115 14 0-QuickFolders-6 6 1-context-menu-missing-read-v1" src="https://github.com/user-attachments/assets/56e5fc8b-1d62-48c6-9aa8-ef3c52150aba">

<img width="609" alt="MacOS-14 6-ThB-115 14 0-QuickFolders-6 6 1-context-menu-missing-read-v2" src="https://github.com/user-attachments/assets/c432728d-9671-499e-ab00-47045659d55e">

(replaced duplicate image with Image of "Options > Tab: General")

**Comment by RealRaven2000** [comment]
It might be caused by no unread mails being in the parent folder (maybe), can you test this? I will find some debug settings for the console to show details when you test.

**Comment by skleiber** [comment]
I thought about that, too. 
I already created testfolders for that:
- parent folder ... copied some emails in it ... marked them as unread
- child folder ... copied some emails in it ... marked them as unread

I also have different accounts, IMAP / POP3 ... i testet on many levels / subdirectories, in Mac nowhere i get the context menu with "mark all read" or the menu with "mark all read + subfolders"

I testet in Windows (Virtual Machine), there it works fine.
