### ISSUE TITLE
Moving multiple messages via quickMove - fails the filter assistant

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#385]
Apparently quickMove fails triggering the filter assistant when moving more than one email using the quickMove.

I found this after following up on issue #354  which prevents displaying the number of message moved. The problem is that the function 

`QuickFolders.Util.moveMessages()`

returns an array that doesn't just contain a flat list of messages but is an Array of arrays. Needs to be fixed and tested ASAP.

**Comment by RealRaven2000** [comment]
The reason this happened - the underlying copy / move functions by THunderbird failed if the message came from differing folders (and you can gather emails from different folders before you actually carry out the quickMove operation). So I broke up the mails into portions with equal source folders (rather than having one copy operation for each message), and then copied the processed messages to a "results" Array,  like this:

```js
          messageIdList.push(origIds);  // <= successfully moved / copied
          QuickFolders.CopyListener.OnStopCopy(status); 
```

I assumed the Array "oridId" would be concatenated to the messageIdList Array, instead it is nested as a member. I need to investigate if there is any unwanted fallout when I fix this (apart from fixing the message issue).

To fix, I should do this instead:

```js
          messageIdList.push(...origIds);  
```

**Comment by RealRaven2000** [comment]
Here are previews for both versions of Thunderbird:

ESR102: [QuickFolders-mx-5.17.1pre6.zip](https://github.com/RealRaven2000/QuickFolders/files/12283218/QuickFolders-mx-5.17.1pre6.zip)

ESR115: [QuickFolders-mx-6.1pre122.zip](https://github.com/RealRaven2000/QuickFolders/files/12283336/QuickFolders-mx-6.1pre122.zip)

--------

To test the versions above, download the zip file, drag the file into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by RealRaven2000** [comment]
Fixed in 6.1 (published 08/08/2023) and 5.17.1 (published 07/08/2023)

**Comment by PotatoCarl** [comment]
It does not work here with neither the 122 pre-version nor the 6.1.1 version. When I move an email with the quickjump function (dropping it on the quickjump button and entering the name of a folder) the message is moved but the filter dialog does not pop up.

Also, I still cannot create new folders with the quickjump function (old bug from me, I did not use it as it did never work here, but tried again and found it still does not work).

**Comment by RealRaven2000** [comment]
Hmm it really looks like a recent change in 6.1 or Thunderbird must have broken it again... Possibly changes in #387. Let me investigate...

**Comment by RealRaven2000** [comment]
> Also, I still cannot create new folders with the quickjump function (old bug from me, I did not use it as it did never work here, but tried again and found it still does not work).

This one works for me (here I am testing on an IMAP folder):

Using Shift+M to trigger quickMove. Entering a new subfolder name in the search box (using the / syntax) and then clicking the create new subfolder menu item (1). This pops up the (2) New Folder dialog (is it shown on your system):

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/b6d80710-61a8-4f35-bd58-70cc9d1f2163)

then I can go to the folder and it takes a few seconds for my server to sync the new folder after which the emails are shown in the new folder:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/0c4a7b7a-901c-4863-ac8a-215c958c28e0)

If there is a problem with this, let's file a new bug please. For the filter assistant, please see my following comment.

**Comment by RealRaven2000** [comment]
> It does not work here with neither the 122 pre-version nor the 6.1.1 version. When I move an email with the quickjump function (dropping it on the quickjump button and entering the name of a folder) the message is moved but the filter dialog does not pop up.

So it seems like there is something different in the message database, I was using the target FOlder (the folder that the email was moved to) in order to retrieve the current messageHdr but that doesn't appear to work, so I fixed that on the quickFilters side. Can you check it with this version please?

[quickFilters-wx-6.1.2pre31.zip](https://github.com/RealRaven2000/QuickFolders/files/12312468/quickFilters-wx-6.1.2pre31.zip)

@PotatoCarl  I might quickly release a maintenance version from that if it works for you.

**Comment by PotatoCarl** [comment]
Great, works again. Thank you.

**Comment by RealRaven2000** [comment]
> Great, works again. Thank you.

thanks for the quick testing!!

**Comment by RealRaven2000** [comment]
AS this is issue was closed on the quickFilters side, I am closing the issue here too.
